export const MAP_REQUEST = 'MAP_REQUEST';
export const MAP_SUCCESS= 'MAP_SUCCESS';
export const MAP_FAIL = 'MAP_FAIL';

//export const MARKER_ONCLICK_REQUEST = 'MARKER_ONCLICK_REQUEST';
export const MARKER_ONCLICK_SUCCESS = 'MARKER_ONCLICK_SUCCESS';
export const MARKER_ONCLICK_FAIL = 'MARKER_ONCLICK_FAIL';

export const MARKER_ONAUTOCOMPLETE_REQUEST = 'MARKER_ONAUTOCOMPLETE_REQUEST';
export const MARKER_ONAUTOCOMPLETE_SUCCESS = 'MARKER_ONAUTOCOMPLETE_SUCCESS';
export const MARKER_ONAUTOCOMPLETE_FAIL = 'MARKER_ONAUTOCOMPLETE_FAIL';

export const GET_MARKER_FROM_LIST_REQUEST = 'GET_MARKER_FROM_LIST_REQUEST';
export const GET_MARKER_FROM_LIST_SUCCESS = 'GET_MARKER_FROM_LIST_SUCCESS';
export const GET_MARKER_FROM_LIST_FAIL = 'GET_MARKER_FROM_LIST_FAIL';