export const UPDATE_MARKER_REQUEST = 'UPDATE_MARKER_REQUEST';
export const UPDATE_MARKER_SUCCESS = 'UPDATE_MARKER_SUCCESS';
export const UPDATE_MARKER_FAIL = 'UPDATE_MARKER_FAIL';

export const GET_CLOSEST_OBJECT_REQUEST = 'GET_CLOSEST_OBJECT_REQUEST';
export const GET_CLOSEST_OBJECT_SUCCESS = 'GET_CLOSEST_OBJECT_SUCCESS';
export const GET_CLOSEST_OBJECT_FAIL = 'GET_CLOSEST_OBJECT_FAIL';



